.TH "dcfg_api::DCFG_LOOP_CONTAINER" 3 "Tue Jun 2 2015" "DCFG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcfg_api::DCFG_LOOP_CONTAINER \- 
.PP
Common interface to any structure containing loops, i\&.e\&., routines, images, and processes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dcfg_api\&.H>\fP
.PP
Inherits \fBdcfg_api::DCFG_GRAPH_BASE\fP\&.
.PP
Inherited by \fBdcfg_api::DCFG_ROUTINE\fP\fC [virtual]\fP, and \fBdcfg_api::DCFG_ROUTINE_CONTAINER\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual UINT32 \fBget_loop_ids\fP (\fBDCFG_ID_CONTAINER\fP &node_ids) const =0"
.br
.RI "\fIGet the set of loop IDs\&. \fP"
.ti -1c
.RI "virtual \fBDCFG_LOOP_CPTR\fP \fBget_loop_info\fP (DCFG_ID loop_id) const =0"
.br
.RI "\fIGet access to data for a loop\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Common interface to any structure containing loops, i\&.e\&., routines, images, and processes\&. 

Note: even though loops can be nested, a loop is not considered a \fBDCFG_LOOP_CONTAINER\fP\&. Loop nesting structure can be determined by querying the parent loop id from a \fBDCFG_LOOP\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual UINT32 dcfg_api::DCFG_LOOP_CONTAINER::get_loop_ids (\fBDCFG_ID_CONTAINER\fP &node_ids) const\fC [pure virtual]\fP"

.PP
Get the set of loop IDs\&. Get IDs of all loops in the structure\&. A loop ID is the same as the ID of the basic block at its head node\&. 
.PP
\fBReturns:\fP
.RS 4
Number of IDs that were added to \fCnode_ids\fP\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fInode_ids\fP Container to which IDs are added\&. Previous contents of the container are \fInot\fP emptied by this call, so it should be emptied by the programmer before the call if desired\&. The programmer can use any implementation of \fBDCFG_ID_CONTAINER\fP: \fBDCFG_ID_VECTOR\fP, \fBDCFG_ID_SET\fP, etc\&. 
.RE
.PP

.SS "virtual \fBDCFG_LOOP_CPTR\fP dcfg_api::DCFG_LOOP_CONTAINER::get_loop_info (DCFG_IDloop_id) const\fC [pure virtual]\fP"

.PP
Get access to data for a loop\&. \fBReturns:\fP
.RS 4
Pointer to interface object for specified loop or \fCNULL\fP if \fCloop_id\fP is invalid\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIloop_id\fP ID of desired loop\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for DCFG from the source code\&.
